In [114]:
from sklearn import datasets
iris= datasets.load_iris()

In [116]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [118]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
import numpy as np
from sklearn import datasets
np.random.seed(0)
iris = datasets.load_iris()
x = iris.data #predictors (features)
y = iris.target #Outcome to be predicted
i = np.random.permutation(len(iris.data))
print(i)
x_train = x[i[:-10]]#140 (all but the last 10)
y_train = y[i[:-10]]#140 (outcome)
x_test = x[i[-10:]]#the last 10
y_test = y[i[-10:]]#the last 10

[114  62  33 107   7 100  40  86  76  71 134  51  73  54  63  37  78  90
  45  16 121  66  24   8 126  22  44  97  93  26 137  84  27 127 132  59
  18  83  61  92 112   2 141  43  10  60 116 144 119 108  69 135  56  80
 123 133 106 146  50 147  85  30 101  94  64  89  91 125  48  13 111  95
  20  15  52   3 149  98   6  68 109  96  12 102 120 104 128  46  11 110
 124  41 148   1 113 139  42   4 129  17  38   5  53 143 105   0  34  28
  55  75  35  23  74  31 118  57 131  65  32 138  14 122  19  29 130  49
 136  99  82  79 115 145  72  77  25  81 140 142  39  58  88  70  87  36
  21   9 103  67 117  47]


In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [19]:
knn.predict(x_test)#predicted y

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [21]:
y_test#actual y

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
pred_y=knn.predict(x_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
print ("f1:" + str(f1_score(pred_y, y_test,average='micro')))
print ("accuracy:" + str(accuracy_score(pred_y, y_test)))
print ("precision:" + str(precision_score(pred_y, y_test,average='micro')))
print ("recall:" + str(recall_score(pred_y, y_test,average='micro')))

f1:0.9
accuracy:0.9
precision:0.9
recall:0.9


In [25]:
from sklearn import svm
svc = svm.SVC().fit(x_train,y_train)
pred_y = svc.predict(x_test)

print ("f1:" + str(f1_score(pred_y, y_test,average='micro')))
print ("accuracy:" + str(accuracy_score(pred_y, y_test)))
print ("precision:" + str(precision_score(pred_y, y_test,average='micro')))
print ("recall:" + str(recall_score(pred_y, y_test,average='micro')))

f1:0.9
accuracy:0.9
precision:0.9
recall:0.9


In [27]:
#Diabetes dataset
from sklearn import datasets
diabetes = datasets.load_diabetes()

In [29]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

In [31]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [33]:
from sklearn import linear_model
linreg = linear_model.LinearRegression()

In [35]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
x_train = diabetes.data[:-20]#all the data strating from the begining but the last 20
y_train = diabetes.target[:-20]
x_test = diabetes.data[-20:]
y_test = diabetes.target[-20:]

In [37]:
linreg.fit(x_train,y_train)

LinearRegression()

In [39]:
linreg.coef_

array([ 3.06094248e-01, -2.37635570e+02,  5.10538048e+02,  3.27729878e+02,
       -8.14111926e+02,  4.92799595e+02,  1.02841240e+02,  1.84603496e+02,
        7.43509388e+02,  7.60966464e+01])

In [41]:
linreg.predict(x_test)#predicted y

array([197.61898486, 155.44031962, 172.88875144, 111.53270645,
       164.79397301, 131.06765869, 259.12441219, 100.47873746,
       117.06005372, 124.30261597, 218.36868146,  61.19581944,
       132.24837933, 120.33293546,  52.54513009, 194.03746764,
       102.5756431 , 123.56778709, 211.03465323,  52.60221696])

In [43]:
y_test#actual y

array([233.,  91., 111., 152., 120.,  67., 310.,  94., 183.,  66., 173.,
        72.,  49.,  64.,  48., 178., 104., 132., 220.,  57.])

In [45]:
linreg.score(x_test, y_test)

0.585085427447195

In [124]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data using train_test_split instead of permutation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [126]:
# KNN Classifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
pred_y_knn = knn.predict(X_test)

print("\nKNN Results:")
print("f1:" + str(f1_score(pred_y_knn, y_test, average='micro')))
print("accuracy:" + str(accuracy_score(pred_y_knn, y_test)))
print("precision:" + str(precision_score(pred_y_knn, y_test, average='micro')))
print("recall:" + str(recall_score(pred_y_knn, y_test, average='micro')))


KNN Results:
f1:1.0
accuracy:1.0
precision:1.0
recall:1.0


In [128]:
# SVM Classifier
svc = SVC()
svc.fit(X_train, y_train)
pred_y = svc.predict(X_test)

print("\nSVM Results:")
print("f1:" + str(f1_score(pred_y, y_test, average='micro')))
print("accuracy:" + str(accuracy_score(pred_y, y_test)))
print("precision:" + str(precision_score(pred_y, y_test, average='micro')))
print("recall:" + str(recall_score(pred_y, y_test, average='micro')))


SVM Results:
f1:1.0
accuracy:1.0
precision:1.0
recall:1.0


In [130]:
# Decision Tree Classifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
pred_y_dtree = dtree.predict(X_test)

print("\nDecision Tree Results:")
print("f1:" + str(f1_score(pred_y_dtree, y_test, average='micro')))
print("accuracy:" + str(accuracy_score(pred_y_dtree, y_test)))
print("precision:" + str(precision_score(pred_y_dtree, y_test, average='micro')))
print("recall:" + str(recall_score(pred_y_dtree, y_test, average='micro')))


Decision Tree Results:
f1:1.0
accuracy:1.0
precision:1.0
recall:1.0
